apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
      - name: mikroserwis-b
        image: juliamoczynska/mikroserwis_b:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-b-service
spec:
  selector:
    app: mikroserwis-b
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
